# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_level_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='tag',
            field=models.CharField(default='native', max_length=30),
            preserve_default=False,
        ),
    ]
