# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_level_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='profiles',
            field=models.ManyToManyField(through='exchange.Link', to='exchange.Profile'),
        ),
        migrations.AddField(
            model_name='link',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exchange.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exchange.Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exchange.Profile'),
            preserve_default=False,
        ),
    ]
