# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20170820_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='level',
            field=models.CharField(choices=[(b'b', b'beginner'), (b'e', b'elementary'), (b'p', b'pre-intermediate'), (b'i', b'intermediate'), (b'u', b'upper-intermediate'), (b'a', b'advanced')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
