# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20170821_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='learninglangs',
            field=models.ManyToManyField(related_name='learningprofiles', through='exchange.Link', to='exchange.Language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nativelangs',
            field=models.ManyToManyField(related_name='nativeprofiles', to='exchange.Language'),
        ),
        migrations.AlterField(
            model_name='link',
            name='level',
            field=models.CharField(choices=[(b'b', b'beginner'), (b'e', b'elementary'), (b'p', b'pre-intermediate'), (b'i', b'intermediate'), (b'u', b'upper-intermediate'), (b'a', b'advanced')], max_length=1),
        ),
    ]
