# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_auto_20170909_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
